FROM scratch
LABEL org.entando.bundle-name="tk2"
ADD .entando/output/descriptors/ .
ADD microfrontends/nodi-table/build widgets/nodi-table
ADD microfrontends/nodi-details/build widgets/nodi-details
ADD microfrontends/nodi-form/build widgets/nodi-form
